# Generated by Django 4.1.5 on 2023-08-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.CharField(max_length=256, unique=True)),
                ('place', models.CharField(max_length=256)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256, unique=True)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('unit', models.CharField(max_length=256)),
                ('sellPrice', models.FloatField(default=0)),
                ('purchasePrice', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('quantityFromLastYear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyEnglishName', models.CharField(max_length=256)),
                ('companyArabicName', models.CharField(max_length=256)),
                ('yearStart', models.DateTimeField()),
                ('taxes', models.IntegerField()),
                ('assestsCalculations', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcationType', models.CharField(choices=[('sell', 'مبيعات'), ('buy', 'مشتريات')], max_length=256)),
                ('totalPrice', models.FloatField()),
                ('tax', models.FloatField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.inventories')),
            ],
        ),
        migrations.CreateModel(
            name='Wastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='finance.items')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('partyType', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=256)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='finance.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.items')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transactions')),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='items',
            field=models.ManyToManyField(related_name='items', through='finance.Transactions_Items', to='finance.items'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.users'),
        ),
        migrations.CreateModel(
            name='ItemsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, unique=True)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('categoryParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.itemscategories')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.itemscategories'),
        ),
        migrations.CreateModel(
            name='ItemPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('transcationType', models.CharField(choices=[('sell', 'مبيعات'), ('buy', 'مشتريات')], max_length=256)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='finance.items')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Wastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('invertory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.inventories')),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.wastes')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.inventories')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.items')),
            ],
        ),
        migrations.AddField(
            model_name='inventories',
            name='items',
            field=models.ManyToManyField(related_name='inventoriesItems', through='finance.Inventory_Items', to='finance.items'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='wastes',
            field=models.ManyToManyField(related_name='inventoriesWastes', through='finance.Inventory_Wastes', to='finance.wastes'),
        ),
    ]
