# Generated by Django 4.1.5 on 2023-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.CharField(max_length=256),
        ),
    ]
