# Generated by Django 4.1.5 on 2023-08-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_transcationtype_transactions_transacationtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemprices',
            old_name='transcationType',
            new_name='transactionType',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='transacationType',
            new_name='transactionType',
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsList', to='finance.inventories'),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoriesList', to='finance.items'),
        ),
        migrations.AlterField(
            model_name='inventory_wastes',
            name='invertory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastesList', to='finance.inventories'),
        ),
        migrations.AlterField(
            model_name='inventory_wastes',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoriesList', to='finance.wastes'),
        ),
        migrations.AlterField(
            model_name='transactions_items',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsList', to='finance.transactions'),
        ),
    ]
