# Generated by Django 4.1.5 on 2023-08-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_transcationtype_itemprices_transactiontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='inventory',
        ),
        migrations.AddField(
            model_name='transactions_items',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.inventories'),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemsList', to='finance.inventories'),
        ),
        migrations.AlterField(
            model_name='inventory_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoriesList', to='finance.items'),
        ),
        migrations.AlterField(
            model_name='inventory_wastes',
            name='invertory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wastesList', to='finance.inventories'),
        ),
        migrations.AlterField(
            model_name='inventory_wastes',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoriesList', to='finance.wastes'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='finance.itemscategories'),
        ),
        migrations.AlterField(
            model_name='transactions_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.items'),
        ),
        migrations.AlterField(
            model_name='transactions_items',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemsList', to='finance.transactions'),
        ),
        migrations.AlterField(
            model_name='wastes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wastes', to='finance.items'),
        ),
    ]
