# Generated by Django 4.2.4 on 2023-09-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_items_quantityfromlastyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactionsList', to='finance.items'),
        ),
    ]
