# Generated by Django 4.2.4 on 2023-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_settings_address_settings_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='yearStart',
            field=models.DateTimeField(null=True),
        ),
    ]
