# Generated by Django 4.2.4 on 2023-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_settings_yearstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='taxes',
            field=models.FloatField(null=True),
        ),
    ]
