# Generated by Django 4.2.4 on 2023-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_settings_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
